### ISSUE TITLE
jsmpp SMPPSession - IOException while reading: null

### ISSUE THREAD

**Issue by SurfVaporizer** [uudashr/jsmpp#46]
I get java.io.EOFException when no activity.
Also i post a questoin in stackoverflow
http://stackoverflow.com/questions/29713934/jsmpp-smppsession-ioexception-while-reading-null

78 [main] INFO org.jsmpp.session.SMPPSession - Connected
83 [PDUReaderWorker: org.jsmpp.session.SMPPSession@71f250e8] INFO org.jsmpp.session.SMPPSession - Starting PDUReaderWorker
java.lang.NullPointerException
    at org.jsmpp.bean.OptionalParameters.get(OptionalParameters.java:238)
    at org.jsmpp.bean.BindResp.getOptionalParameter(BindResp.java:61)
    at org.jsmpp.session.SMPPSession.sendBind(SMPPSession.java:298)
    at org.jsmpp.session.SMPPSession.connectAndBind(SMPPSession.java:234)
    at org.jsmpp.session.SMPPSession.connectAndBind(SMPPSession.java:201)
    at org.jsmpp.examples.SimpleSubmitExample.main(SimpleSubmitExample.java:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

848 [main] INFO org.jsmpp.session.SMPPSession - Changing processor degree to 3

858 [EnquireLinkSender: org.jsmpp.session.SMPPSession@71f250e8] INFO org.jsmpp.session.AbstractSession - Starting EnquireLinkSender

Message submitted, message_id is f46d05f3

3706 [PDUReaderWorker: org.jsmpp.session.SMPPSession@71f250e8] WARN org.jsmpp.session.SMPPSession - IOException while reading: null
java.io.EOFException
    at java.io.DataInputStream.readInt(DataInputStream.java:392)
    at org.jsmpp.DefaultPDUReader.readPDUHeader(DefaultPDUReader.java:40)
    at org.jsmpp.session.SMPPSession$PDUReaderWorker.readPDU(SMPPSession.java:619)
    at org.jsmpp.session.SMPPSession$PDUReaderWorker.run(SMPPSession.java:602)
3707 [PDUReaderWorker: org.jsmpp.session.SMPPSession@71f250e8] INFO org.jsmpp.session.AbstractSession - AbstractSession.close() called
3858 [EnquireLinkSender: org.jsmpp.session.SMPPSession@71f250e8] INFO org.jsmpp.session.AbstractSession - EnquireLinkSender stop
3858 [PDUReaderWorker: org.jsmpp.session.SMPPSession@71f250e8] INFO org.jsmpp.session.AbstractSession - AbstractSession.close() called
3858 [PDUReaderWorker: org.jsmpp.session.SMPPSession@71f250e8] INFO org.jsmpp.session.SMPPSession - PDUReaderWorker stop

**Comment by cforno** [comment]
Hi,

Did you manage to solve the "IOException while reading: null"

I have same issue, and connection is being closed after a while. I was not able to fix until now. Any idea you have about this would be great,

Thanks

**Comment by SurfVaporizer** [comment]
@cforno I don't remember right now but it was a stupid mistake like credentials or something. THe library working good.
