### ISSUE TITLE
Timeout for Appx. first 2 mins after server start on centos. Works well on ubuntu.

### ISSUE THREAD

**Issue by dhanasekarans** [uudashr/jsmpp#55]
I am trying use this jsmpp library to run smpp server as well as client.

The below code has been used as server with little bit modification to accept optional parameters.

https://github.com/uudashr/jsmpp/blob/master/jsmpp-examples/src/main/java/org/jsmpp/examples/SMPPServerSimulator.java

The below code has been used as client with little bit modification to send optional parameters.

https://github.com/uudashr/jsmpp/blob/master/jsmpp-examples/src/main/java/org/jsmpp/examples/SimpleSubmitExample.java

On centos 7.2, I am getting this exception while sending message.  After around 2 mins of the server start, the requests are successful and it picks up the messages send even during the exception.  This doesnt seems to occur on Ubuntu.

Response timeout
org.jsmpp.extra.ResponseTimeoutException: No response after waiting for 2000 millis when executing submit_sm with sessionId 5dc04292 and sequenceNumber 2
	at org.jsmpp.session.AbstractSession.executeSendCommand(AbstractSession.java:261)
	at org.jsmpp.session.SMPPSession.submitShortMessage(SMPPSession.java:321)
	at Smpp.main(Smpp.java:83)
Caused by: org.jsmpp.extra.ResponseTimeoutException: No response after 2000 millis
	at org.jsmpp.extra.PendingResponse.waitDone(PendingResponse.java:117)
	at org.jsmpp.session.AbstractSession.executeSendCommand(AbstractSession.java:257)
	... 2 more

Please help.

Thanks.

**Comment by Tilekbekova** [comment]
did you solve this problem if so how can you help?
